test_name:  Get Store

marks:
    - POS

stages:

    -   name: Get All Stores

        request:
            url: "{protocol:s}://{domain:s}.{preprod_url:s}/retail/store"
            method: GET

        response:
            status_code: 200
            verify_response_with:
                -   function: testing_utils:check_jsonpath_value
                    extra_kwargs:
                        json_path_value: {
                            "msg": "Store Details"
                        }
---
test_name:  Get Store

marks:
    - POS

stages:

    -   name: Add API Name

        request:
            url: "{protocol:s}://{domain:s}.{preprod_url:s}/retail/storeee"
            method: GET

        response:
            status_code: 404
---
test_name:  Get Store

marks:
    - POS

stages:

    -   name: Adding invalid paramtere to API

        request:
            url: "{protocol:s}://{domain:s}.{preprod_url:s}/retail/store?bcs"
            method: GET

        response:
            status_code: 400
            verify_response_with:
                -   function: testing_utils:check_jsonpath_value
                    extra_kwargs:
                        json_path_value: {
                            "result.employees.store_code": "store21"
                        }